lea927/drop-that-beat

- app/models/room.rb
- app/models/room_track.rb
- db/migrate/20210913155353_create_rooms.rb
- db/migrate/20210913155524_add_room_ref_to_room_tracks.rb
- db/schema.rb
- spec/models/room_spec.rb
- test/factories/rooms.rb
> Room model feature

- .env
- .gitignore
- Gemfile
- Gemfile.lock
- app/assets/stylesheets/tracks.scss
- app/controllers/tracks_controller.rb
- app/helpers/tracks_helper.rb
- app/views/tracks/index.html.haml
- config/routes.rb
> Connect to API

- app/mailers/application_mailer.rb
- app/models/user.rb
- app/views/devise/mailer/confirmation_instructions.html.erb
- config/environments/development.rb
- config/environments/test.rb
- config/initializers/devise.rb
- db/migrate/20210914162347_add_confirmable_to_devise.rb
- db/schema.rb
- spec/system/create_user_spec.rb
Closes #21 
resource: https://github.com/heartcombo/devise/wiki/How-To:-Add-:confirmable-to-Users
> Devise confirmable

- db/migrate/20210915115623_add_rounds_to_room.rb
- db/schema.rb
- spec/models/room_spec.rb
> [WIP] Room model add rounds attribute

- db/migrate/20210915131108_add_points_to_user.rb
- db/schema.rb
- spec/models/users_spec.rb
> Update user model to add points attribute

- app/controllers/application_controller.rb
- app/views/devise/sessions/new.html.erb
- config/initializers/devise.rb
- spec/system/login_users_spec.rb
> User login feature

- app/views/devise/registrations/edit.html.erb
- app/views/layouts/_header.html.haml
- spec/system/create_user_spec.rb
- spec/system/edit_password_spec.rb
> Edit password

- Gemfile
- Gemfile.lock
- app/models/track.rb
- db/migrate/20210916121702_change_adam_id_column_to_string.rb
- db/schema.rb
- spec/models/track_spec.rb
- test/factories/tracks.rb
Closes #35 
Please run ```bundle install``` for Hirb gem.
1.) Create room
2.) Create track
3.) Push room to track created through collection.
1.) Hi @annagabriel-hash  I had to declare line # 18 in a different context to fix this rubocop issue.
> Track model update

- app/controllers/rooms_controller.rb
- app/models/room.rb
- app/views/layouts/_header.html.haml
- app/views/rooms/index.html.haml
- spec/system/search_game_rooms_spec.rb
- test/factories/rooms.rb
Closes #39 
Room Model:
---
Rooms Controller:
---
Rooms index view:
---
Resource: 
- Creating a search form: https://medium.com/@yassimortensen/simple-search-form-in-rails-8483739e4042
- Create array from collection proxy: https://stackoverflow.com/questions/24427379/create-array-from-activerecords-association-collectionproxy
**Track.where(artist: search).map(&:rooms)**
**Track.where(artist: search).map(&:rooms).flatten**
> Search rooms

- Gemfile
- Gemfile.lock
- app/controllers/tracks_controller.rb
- app/helpers/application_helper.rb
- app/views/tracks/index.html.haml
- config/routes.rb
Closes #40 
1. If you want to skip the confirmable module in Devise, execute ```User.find(id).skip_confirmation!``` on rails console.
2. Since the results of the search isn't on the UI yet please add a ```byebug``` on line 12 of Tracks controller (see below) then enter ```@tracks``` on rails console upon debugging (during rails s).
> [WIP] Search track

- app/models/track.rb
- spec/models/track_spec.rb
> Callback for saving track attributes as lowercase

- app/controllers/home_page_controller.rb
- app/controllers/rooms_controller.rb
- app/models/room.rb
- app/views/home_page/index.html.haml
- app/views/rooms/edit.html.haml
- spec/models/room_spec.rb
- spec/support/create_game_room.rb
- spec/support/sign_in_user.rb
- spec/system/create_game_rooms_spec.rb
- spec/system/list_game_rooms_spec.rb
- spec/system/search_game_rooms_spec.rb
- spec/system/setup_game_rooms_spec.rb
> Create game room feature

- app/controllers/home_page_controller.rb
- app/controllers/rooms_controller.rb
- config/routes.rb
> Fixes route to home page index

- app/controllers/tracks_controller.rb
- app/views/rooms/edit.html.haml
- app/views/tracks/_search_tracks.html.haml
- app/views/tracks/_track.html.haml
- app/views/tracks/create.js.erb
- app/views/tracks/search.js.erb
- config/routes.rb
- config/webpack/environment.js
- spec/rails_helper.rb
- spec/requests/tracks_controllers_spec.rb
- test/factories/rooms.rb
- test/factories/tracks.rb
- test/factories/users.rb
> Add tracks to room using AJAX

- app/controllers/tracks_controller.rb
- app/views/rooms/edit.html.haml
- app/views/tracks/_track.html.haml
- config/routes.rb
- spec/requests/tracks_controllers_spec.rb
Closes #54
https://user-images.githubusercontent.com/79251819/134309707-5c6a500c-9da9-4ade-a2e0-acfdc0c6e37e.mov
> Remove tracks from rooms feature

- app/controllers/tracks_controller.rb
- app/models/room_track.rb
- db/migrate/20210922083440_add_index_to_room_tracks.rb
- db/schema.rb
- spec/models/room_spec.rb
- spec/requests/tracks_controllers_spec.rb
Closes #59
https://user-images.githubusercontent.com/79251819/134325401-bb48e66e-a0be-4193-9794-952e2bb5f5ec.mov
> Validation for assigning duplicate tracks to room

- app/models/room.rb
- app/views/rooms/edit.html.haml
- spec/models/room_spec.rb
- spec/support/create_game_room.rb
- spec/system/setup_game_rooms_spec.rb
> Max game rounds

- app/controllers/rooms_controller.rb
- app/models/room.rb
- spec/system/search_game_rooms_spec.rb
Closes #60 
Note: View issue for preview of first bug case
2nd Bug:
---
**Case:** When searching for an artist, it only returns rooms with an exact artist. Does not consider track with multiple featuring artists.
Fixes:
---
> Search rooms by artist

- app/controllers/rooms_controller.rb
- app/javascript/packs/application.js
- app/javascript/packs/playlist.js
- app/views/rooms/show.html.haml
> Playlist feature to play playlist upon clicking of start game button

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/user-story.md
> Add github issue templates for standard documentation

- app/models/room.rb
- app/models/track.rb
Fixes #72
Note: All existing tracks were destroyed
https://user-images.githubusercontent.com/79251819/134772844-2b98586c-ff94-4e91-8a60-b0434cf8fc91.mov
https://user-images.githubusercontent.com/79251819/134772821-96e2a14f-1d9a-4ece-a398-4b71eadbede8.mov
> Save track case based on the search result and perform case-insensitive search of rooms

- app/controllers/tracks_controller.rb
- app/views/rooms/_room.json.jbuilder
- app/views/rooms/index.json.jbuilder
- app/views/rooms/show.json.jbuilder
- app/views/tracks/_track.json.jbuilder
- app/views/tracks/index.json.jbuilder
- app/views/tracks/show.json.jbuilder
- spec/requests/tracks_controllers_spec.rb
To display the json file in the browser, sign in the app, then use the following url path:
| Controller#Action | Format | Example |
| --- | --- | --- |
| track#index | /tracks.json | /tracks.json |
| track#show | /tracks/<track_id>.json | /tracks/1.json |
| room#index | /rooms.json | /rooms.json |
| room#show | /rooms/<room_id>.json | /room/1.json |
> Room and tracks json files to easily obtain data via AJAX

- app/views/rooms/show.html.haml
> Stop music when user exists the game room

- app/javascript/packs/model/track.js
Create track class in javascript to easily access the data
| Properties | Data Type | Definition
| --- | ---| --- |
| id | integer | track id | 
| name | string | track name | 
| artist | string | track artist | 
| adam_id | string | track adam_id | 
| preview_url | string | track preview_url | 
| isCorrect | boolean | defines if the track is the correct track |
| Methods | Arguments | Definition | Return value
| --- | ---| ---| --- |
| `createCorrectTrack` | Track object | creates a correct track by setting the property isCorrect to true | Track class 
| `createinCorrectTrack` | Array of incorrect track objects | creates a correct track by setting the property isCorrect to true | Track class
> Create track class in javascript

- app/javascript/packs/model/question.js
- app/javascript/packs/model/track.js
Create question class in javascript to setup list of questions to be shown in the game room and related choices
| Properties | Data Type | Definition
| --- | ---| --- |
| track | Track object | Track object with track details | 
| incorrectTracks | Array of Track object | Track object with track details | 
| noOfChoices | integer | Set number of choices to be displayed | 
| choices | Array of Track object | choices to be displayed in the room | 
| Methods | Arguments | Definition | Return value
| --- | ---| ---| --- |
| `create` | correctTrack, indexOfCorrectTrack, tracks | creates a question class | Question class 
| `getIncorrectTracks` | indexOfCorrectTrack, tracks | Gets the incorrectTracks based on the list of tracks by removing the correct track | Array of incorrect tracks
| Methods …
> Create question class

- app/javascript/packs/model/question.js
- app/javascript/packs/model/room.js
Create room class in javascript to setup rooms in the room model
| Properties | Data Type | Definition
| --- | ---| --- |
| id | number | room id based on the db | 
| name | string | room name | 
| rounds | number | number of rounds to be played | 
| tracks | Array of Track object | tracks in the room | 
| questions | Array of Question object | questions in the room | 
| Methods | Arguments | Definition | Return value
| --- | ---| ---| --- |
| `createQuestions` | tracks | creates questions based on the tracks | Array of Question class
> Create room class in javascript

- Procfile
> Bump Heroku Fix (1)

- app/helpers/application_helper.rb
> Bump Heroku Fix (3)

- config/application.rb
> Bump Heroku Fix (4)

- config/application.rb
> Bump Heroku Fix (5)

- app/helpers/application_helper.rb
> Bump Heroku Fix (6)

- config/application.rb
> Bump Heroku Fix (7)

- config/application.rb
> Bump Heroku Fix (8)

- app/helpers/application_helper.rb
> Bump Heroku Fix (9)

- app/controllers/rooms_controller.rb
- app/javascript/packs/api/index.js
- app/javascript/packs/api/request.js
- app/javascript/packs/api/room.js
- app/javascript/packs/api/url.js
- app/views/rooms/show.html.haml
- spec/requests/rooms_spec.rb
> Update posting of answers feature

- app/javascript/packs/game.js
- app/views/rooms/show.html.haml
> Fix playlist playing multiple times

- app/javascript/packs/game.js
- app/views/rooms/show.html.haml
This prevents the playlist from playing twice 
Fixes #118
> Clear cache when user suddenly exists while playing the game

- config/environments/development.rb
- config/environments/production.rb
> Prod mailer

- app/javascript/packs/game.js
- app/javascript/packs/model/question.js
- app/javascript/packs/playlist.js
- app/views/rooms/show.html.haml
Closes #122 
https://user-images.githubusercontent.com/79251819/135897995-275a10be-7ca8-4378-9b29-5c35e9cf3abf.mov
https://user-images.githubusercontent.com/79251819/135898148-bd8cb0c4-b609-444d-a469-1b04c385f1fd.mov
https://user-images.githubusercontent.com/79251819/135898277-2ba22026-191c-4b24-8383-1b66f1eb26eb.mov
> Display answer feature

- app/javascript/packs/game.js
- app/views/layouts/_header.html.haml
- app/views/rooms/show.html.haml
https://user-images.githubusercontent.com/79251819/136003232-da69258b-3501-4272-abf4-189e0188f99b.mov
https://user-images.githubusercontent.com/79251819/136003409-19e4286e-2145-4469-af36-601dc76da570.mov
https://user-images.githubusercontent.com/79251819/136003576-1464679e-0bba-4e40-b275-477b555bbc81.mov
> Display earned points feature
